services:
  # PostgreSQL Database
  - name: database
    type: pserv
    plan: free
    postgres:
      version: "14"

  # Redis instance for Celery
  - name: redis
    type: redis
    plan: free

  # Django Web Server (Gunicorn)
  - name: web
    type: web
    plan: free
    env: python
    pythonVersion: "3.12"
    buildCommand: "./build.sh"
    # --- THE FIX IS HERE ---
    startCommand: "python manage.py migrate && gunicorn clinic_token_system.wsgi"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"

  # Celery Background Worker
  - name: worker
    type: worker
    plan: free
    env: python
    pythonVersion: "3.12"
    buildCommand: "./build.sh"
    startCommand: "celery -A clinic_token_system.celery worker -P gevent --loglevel=info"
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: database
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"