# Generated by Django 5.2.5 on 2025-10-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='distance_km',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='token_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
